### PR TITLE
Added cooldown timer to home and warp commands. Closes #163

### LINKED ISSUE #163: Add home and warp cooldown timer
It would be useful to have the option to have the following:

cooldown (time between being able to use home) Ex: 10 minutes
warmup (time to not move/take damage before home fires) Ex:15 seconds

This would help from people using home as a getaway.

### PR DESCRIPTION
**Pull request by MinecraftXwinP**
This is related to #163 
I would like to add pending phase to home command too.

But I think I should try to submit this little PR first to see if the style is OK.

Permission node added: ftbutilities.homes.cooldown
Lang key added: ftbutilities.lang.homes.in_cooldown

### CODE REVIEW

**Comment by LatvianModder** [comment]
Very nice, but some changes I request:
1. Instead of `new Date().getTime();` use ticks, from `server.getWorld(0).getTotalWorldTime()`
2. First rank config to `new ConfigInt(12000, 0, Integer.MAX_VALUE)` so it can't be negative
3. Lang value to `You can only use home in %s!`
4. Cooldown int param in lang value to StringUtils.getTimeStringTicks(cooldown)
5. Optional - also the same principle cooldown for /warp?

**Comment by MinecraftXwinP** [comment]
Made timer base on ticks. But I am wondering how to preserve the timer over server restart. Maybe serializing cooldown to NBT when save? Or this feature is actually trivial?

**Comment by LatvianModder** [comment]
Oh, I didn't realize you don't do that. Yeah, serialize it with "LastHomeTime" or smth

**Comment by LatvianModder** [comment]
p.s. you don't need to add min/max in 2nd ConfigInt, it will be copied to it

**Comment by MinecraftXwinP** [comment]
I found that the implementation preserve timer over log in and log out XD . Is this desired?

**Comment by MinecraftXwinP** [comment]
I would like to add cooldown timer to other tp commands too. But it's late here,so I might work on it tomorrow. BTW, thanks for the suggestions. Learned a lot.

**Comment by LatvianModder** [comment]
Ah, just noticed you got the wrong idea of serialization. Just serialize the absolute time, `nbt.setLong("LastGoHome", lastGoHome);` and `lastGoHome = nbt.getLong("LastGoHome");`

**Comment by MinecraftXwinP** [comment]
Sorry. I though it's relative to uptime. I changed it back.

**Pull request merged**
